version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "all"
    automerge: true
    automerge-type: "branch"
    # Only allow auto-merge for non-breaking updates via GitHub dependency graph
    # NOTE: GitHub respects semver ranges and will label PRs accordingly.
    # For added safety, we rely on branch protection requiring CI to pass before merge.
