name: CI - Secrets Presence Check

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  check-secrets:
    # Do not run this job for forked PRs because repository secrets are not available to forks
    if: ${{ github.event.pull_request == null || github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fail if required secrets missing
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          set -e
          missing=0

          if [ -z "$GEMINI_API_KEY" ]; then
            echo "Missing secret: GEMINI_API_KEY"
            missing=1
          fi

          # Android keystore secrets: require all-or-none. If ANDROID_KEYSTORE_BASE64 provided, ensure the rest exist.
          if [ -n "$ANDROID_KEYSTORE_BASE64" ]; then
            for var in ANDROID_KEYSTORE_BASE64 KEYSTORE_PASSWORD KEY_ALIAS KEY_PASSWORD; do
              eval val="\$$var"
              if [ -z "$val" ]; then
                echo "Missing android secret: $var"
                missing=1
              fi
            done
          fi

          if [ "$missing" -eq 1 ]; then
            echo "One or more required secrets are missing"
            exit 1
          fi
